#<font face="gotham" color="yellow">Problem Statement:
#<font face="gotham" color="yellow">Take any two matrices of suitable order and perform following operations
##<font face="gotham" color="yellow">1. Addition
##<font face="gotham" color="yellow">2. Substraction
##<font face="gotham" color="yellow">3. Multiplication
##<font face="gotham" color="yellow">4. Transpose
##<font face="gotham" color="yellow">5. find inverse for each matrix



# <font face="gotham" color="pink"> Note
##<font face="gotham" color="pink">1. make a copy of this file.
##<font face="gotham" color="pink">2. Each part has some sample examples just for your reference, you need to add your own examples</font>


In [ ]:
import numpy as np
import sympy as sy
sy.init_printing()

In [ ]:
def round_expr(expr, num_digits):
    return expr.xreplace({n : round(n, num_digits) for n in expr.atoms(sy.Number)})

# <font face="gotham" color="yellow"> Matrix Operations</font>

Matrix _addition_ operations are straightforward:
1. $A+ B= B+ A$
2. $(A+B)+ C=A+(B+C)$
3. $c(A+B)=cA+cB$
4. $(c+d)A=cA+c{D}$
5. $c(dA)=(cd)A$
6. $A+{0}=A$, where ${0}$ is the zero matrix
7. For any $A$, there exists an $- A$, such that $ A+(- A)=0$.

They are as obvious as it looks, so no proofs are provided. And the matrix _multiplication_ properties are:
1. $ A({BC})=({AB}) C$
2. $c({AB})=(cA)B=A(cB)$
3. $A(B+ C)={AB}+{AC}$
4. $(B+C)A={BA}+{CA}$

Note that we need to differentiate between two types of multiplication: _Hadamard multiplication_, denoted as $A \odot B$ (element-wise multiplication), and _matrix multiplication_, denoted simply as $AB$.

#This is Sample Example

In [ ]:
A = np.array([[1, 2], [3, 4]])    #sample example
B = np.array([[5, 6], [7, 8]])

In [ ]:
A*B # this is Hadamard elementwise product

array([[ 5, 12],
       [21, 32]])

In [ ]:
A@B # this is matrix product

array([[19, 22],
       [43, 50]])

#<font face="gotham" color="yellow">Examples

In [ ]:
##Write your code here

## <font face="gotham" color="yellow"> SymPy Demonstration: Addition </font>

Let's define all the letters as symbols in case we need to use them repeatedly. With this library, we can perform computations analytically, making it a valuable tool for learning linear algebra.

In [ ]:
A = sy.Matrix([[1, 2, 3], [4, 5, 6]])     #sample example
A + A, A - A

⎛⎡2  4   6 ⎤  ⎡0  0  0⎤⎞
⎜⎢         ⎥, ⎢       ⎥⎟
⎝⎣8  10  12⎦  ⎣0  0  0⎦⎠

#<font face="gotham" color="yellow">Examples

In [ ]:
##Write your code here

## <font face="gotham" color="Yellow"> SymPy Demonstration: Multiplication </font>

The matrix multiplication rules can be clearly understood by using symbols.

In [ ]:
A = sy.Matrix([[1, 2, 3], [4, 5, 6]])                                 #sample example
B = sy.Matrix([[1, 2, 3], [4, 5, 6], [-1, 0, 3]])
A, B

⎛           ⎡1   2  3⎤⎞
⎜⎡1  2  3⎤  ⎢        ⎥⎟
⎜⎢       ⎥, ⎢4   5  6⎥⎟
⎜⎣4  5  6⎦  ⎢        ⎥⎟
⎝           ⎣-1  0  3⎦⎠

In [ ]:
AB = A*B; AB

⎡6   12  24⎤
⎢          ⎥
⎣18  33  60⎦

#<font face="gotham" color="yellow">Examples

In [ ]:
##Write your code here

## <font face="gotham" color="yellow"> Commutability </font>

Matrix multiplication usually does not commute, meaning ${AB} \neq {BA}$. For instance, consider matrices $A$ and $B$:

In [ ]:
A = sy.Matrix([[3, 4], [7, 8]])             #sample example
B = sy.Matrix([[5, 3], [2, 1]])
A*B, B*A

⎛⎡23  13⎤  ⎡36  44⎤⎞
⎜⎢      ⎥, ⎢      ⎥⎟
⎝⎣51  29⎦  ⎣13  16⎦⎠

#<font face="gotham" color="yellow">Examples

In [ ]:
##Write your code here

How do we find a commutable matrix? Let's try find out analytically

# <font face="gotham" color="yellow"> Transpose of Matrices </font>

Matrix $A_{n\times m}$ and its transpose is

In [ ]:
A = sy.Matrix([[1, 2, 3], [4, 5, 6]]); A              #sample example
A.transpose()

⎡1  4⎤
⎢    ⎥
⎢2  5⎥
⎢    ⎥
⎣3  6⎦

#<font face="gotham" color="yellow">Examples

In [ ]:
##Write your code here

The properties of transpose are
1. $(A^T)^T$
2. $(A+B)^T=A^T+B^T$
3. $(cA)^T=cA^T$
4. $(AB)^T=B^TA^T$

We can show why the last property holds with SymPy, define $A$ and $B$, multiply them, then transpose, that means $(AB)^T$

In [ ]:
A = sy.Matrix([[1, 2], [3, 4], [5, 6]])               #sample example
B = sy.Matrix([[1, 2, 3], [4, 5, 6]])
AB = A*B
AB_t = AB.transpose(); AB_t

⎡9   19  29⎤
⎢          ⎥
⎢12  26  40⎥
⎢          ⎥
⎣15  33  51⎦

Transpose $A$ and $B$, then multiply, meaning $B^TA^T$

In [ ]:
B_t_A_t = B.transpose()*A.transpose()
B_t_A_t

⎡9   19  29⎤
⎢          ⎥
⎢12  26  40⎥
⎢          ⎥
⎣15  33  51⎦

Check if they are equal

In [ ]:
AB_t == B_t_A_t

True

#<font face="gotham" color="yellow">Examples

In [ ]:
##Write your code here

# <font face="gotham" color="Yellow"> Identity Matrices </font>

This is an identity matrix $I_5$, only $1$'s on principal diagonal, all rest elements are $0$'s.

In [ ]:
sy.eye(5)                 #sample example

⎡1  0  0  0  0⎤
⎢             ⎥
⎢0  1  0  0  0⎥
⎢             ⎥
⎢0  0  1  0  0⎥
⎢             ⎥
⎢0  0  0  1  0⎥
⎢             ⎥
⎣0  0  0  0  1⎦

Identity matrix properties:

$$
AI=IA = A
$$

Let's generate $ I$ and $ A$ and show if it holds

In [ ]:
I = np.eye(5); I                #sample example

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
A = np.around(np.random.rand(5, 5)*100); A # generate a random matrix

array([[52., 78., 83., 79., 75.],
       [37., 44.,  5.,  7., 79.],
       [32., 32., 50., 51., 34.],
       [77., 79., 15.,  9., 24.],
       [76., 46., 18.,  4., 24.]])

Check if they are equal

In [ ]:
(A@I == I@A).all()

np.True_

# <font face="gotham" color="Yellow"> Inverse Matrices </font>

If ${AB}={BA}=\mathbf{I}$, $ B$ is called the inverse of matrix $  A$, denoted as $ B=  A^{-1}$.


NumPy has convenient function ```np.linalg.inv()``` for computing inverse matrices. Generate $ A$

In [ ]:
A = np.round(10*np.random.randn(5,5)); A              #sample example

array([[ -7.,  10., -10.,   3.,  12.],
       [-13., -15.,  18.,  16.,   7.],
       [  2.,  -3., -15.,  -6., -11.],
       [ -3.,  -9.,  -1.,   2.,   4.],
       [  6.,   3., -11.,   5., -15.]])

In [ ]:
Ainv = np.linalg.inv(A); Ainv

array([[-3.99884800e-02, -8.04013816e-02, -1.28264400e-01,
         1.54216648e-01,  6.56735705e-02],
       [ 2.54577217e-02,  7.73622193e-03, -7.76843250e-05,
        -9.62357208e-02, -1.62947609e-03],
       [-2.61417227e-02,  1.60958132e-02, -9.22359254e-03,
        -6.03777732e-02, -2.27387704e-02],
       [ 1.49836010e-02,  4.25558522e-03, -6.49459904e-02,
         5.67853468e-02,  7.67426394e-02],
       [ 1.32612827e-02, -4.09983762e-02, -6.62059923e-02,
         1.05644998e-01,  1.53284436e-03]])

Verify if they are truly inverse of each other

In [ ]:
A@Ainv

array([[ 1.00000000e+00,  1.11022302e-16, -1.11022302e-16,
         1.66533454e-16,  6.24500451e-17],
       [-3.81639165e-17,  1.00000000e+00,  2.22044605e-16,
         1.52655666e-16, -5.37764278e-17],
       [ 2.42861287e-17, -1.38777878e-17,  1.00000000e+00,
        -2.08166817e-16,  5.20417043e-18],
       [ 0.00000000e+00,  5.55111512e-17,  1.11022302e-16,
         1.00000000e+00, -6.93889390e-18],
       [ 6.59194921e-17, -1.80411242e-16,  1.11022302e-16,
         1.80411242e-16,  1.00000000e+00]])

The ```-0.``` means there are more digits after point, but omitted here.

#<font face="gotham" color="yellow">Examples

In [ ]:
##Write your code here